export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_REQUEST_IN_PROGRESS = 'POSTS_REQUEST_IN_PROGRESS';
export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';
export const POSTS_REQUEST_FAILURE = 'POSTS_REQUEST_FAILURE';
