export const WEATHER_FORECASTS_REQUEST = 'WEATHER_FORECASTS_REQUEST';
export const WEATHER_FORECASTS_IN_PROGRESS = 'WEATHER_FORECASTS_IN_PROGRESS';
export const WEATHER_FORECASTS_SUCCESS = 'WEATHER_FORECASTS_SUCCESS';
export const WEATHER_FORECASTS_FAILURE = 'WEATHER_FORECASTS_FAILURE';
